spring:
  application:
    name: mock-persistence-chat
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/social-chat-db

server:
  port: 8898

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

# development Profile
---
spring:
  profiles: dev
  data:
    mongodb:
      host: set-mongo-dev.digitalharbor.us
      port: 27017
      uri: mongodb://set-mongo-dev.digitalharbor.us:27017/social-chat-db

server:
  port: 8898

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true

# Qa Profile
---
spring:
  profiles: qa
  data:
    mongodb:
      host: set-mongo-qa.digitalharbor.us
      port: 27017
      uri: mongodb://set-mongo-qa.digitalharbor.us:27017/social-chat-db

server:
  port: 8898

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true

# Production Profile
---
spring:
  profiles: production


# development Profile (local)
---
spring:
  profiles: devlocal
  data:
    mongodb:
      host: mongo
      port: 27017
      uri: mongodb://mongo:27017/social-chat-db

server:
  port: 8898

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true

