# local Profile
spring:
  application:
    name: mock-persistence-resources
  data:
      mongodb:
        host: localhost
        port: 27017
        uri: mongodb://localhost:27017/mock-resources-db
server:
  port: 8585

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

# development Profile
---
spring:
  profiles: development
  data:
    mongodb:
      host: 10.0.3.24
      port: 27017
      uri: mongodb://10.0.3.24:27017/social-chat-db

server:
  port: 8585

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

# Qa Profile
---
spring:
  profiles: qa

# Production Profile
---
spring:
  profiles: production