spring:
  application:
    name: social-chat
  rabbitmq:
    host: set-docker-dev-n2.digitalharbor.us
    port: 5672
    username: guest
    password: guest
server:
  port: 8881

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
          enabled: true

#    host: set-docker-dev-n2.digitalharbor.us
#    port: 5672
# to avoid java.util.concurrent.TimeoutException on first hystrix execution
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

spring.cloud.stream.bindings.emailNotificationOutput.destination: emailNotificationTopic
spring.cloud.stream.bindings.emailNotificationOutput.content-type: application/json

spring.cloud.stream.bindings.msgNotificationOutput.destination: messageNotificationTopic
spring.cloud.stream.bindings.msgNotificationOutput.content-type: application/json

cors:
  allowOrigin: '*'

stompBroker:
    port: 61613

logging.level.com.dharbor.set.social.chat: DEBUG
logging.level.com.dharbor.set.social.common.notifications: DEBUG

# development Profile
---
spring:
  profiles: dev
  rabbitmq:
    host: set-docker-dev-n2.digitalharbor.us
    port: 5672
    username: guest
    password: guest

server:
  port: 8881

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
          enabled: true

# to avoid java.util.concurrent.TimeoutException on first hystrix execution
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

spring.cloud.stream.bindings.emailNotificationOutput.destination: emailNotificationTopic
spring.cloud.stream.bindings.emailNotificationOutput.content-type: application/json

spring.cloud.stream.bindings.msgNotificationOutput.destination: messageNotificationTopic
spring.cloud.stream.bindings.msgNotificationOutput.content-type: application/json

cors:
  allowOrigin: '*'

stompBroker:
    port: 61613

logging.level.com.dharbor.set.social.chat: DEBUG
logging.level.com.dharbor.set.social.common.notifications: DEBUG


# Qa Profile
---
spring:
  profiles: qa
  rabbitmq:
    host: set-docker-qa-n1.digitalharbor.us
    port: 5672
    username: guest
    password: guest
server:
  port: 8881
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
          enabled: true
# to avoid java.util.concurrent.TimeoutException on first hystrix execution
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
spring.cloud.stream.bindings.emailNotificationOutput.destination: emailNotificationTopic
spring.cloud.stream.bindings.emailNotificationOutput.content-type: application/json
spring.cloud.stream.bindings.msgNotificationOutput.destination: messageNotificationTopic
spring.cloud.stream.bindings.msgNotificationOutput.content-type: application/json
cors:
  allowOrigin: '*'
stompBroker:
    port: 61613
logging.level.com.dharbor.set.social.chat: DEBUG
logging.level.com.dharbor.set.social.common.notifications: DEBUG

# Production Profile
---
spring:
  profiles: production
  
# Production Profile
---
spring:
  profiles: dh-bo
  rabbitmq:
    host: 172.16.4.39
    port: 5672
    username: guest
    password: guest

server:
  port: 8881

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
          enabled: true

# to avoid java.util.concurrent.TimeoutException on first hystrix execution
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

spring.cloud.stream.bindings.emailNotificationOutput.destination: emailNotificationTopic
spring.cloud.stream.bindings.emailNotificationOutput.content-type: application/json

spring.cloud.stream.bindings.msgNotificationOutput.destination: messageNotificationTopic
spring.cloud.stream.bindings.msgNotificationOutput.content-type: application/json

cors:
  allowOrigin: http://localhost:9191

logging.level.com.dharbor.set.social.chat: DEBUG
logging.level.com.dharbor.set.social.common.notifications: DEBUG


# development Profile (local)
---
spring:
  profiles: devlocal
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8881

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
          enabled: true

# to avoid java.util.concurrent.TimeoutException on first hystrix execution
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

spring.cloud.stream.bindings.emailNotificationOutput.destination: emailNotificationTopic
spring.cloud.stream.bindings.emailNotificationOutput.content-type: application/json

spring.cloud.stream.bindings.msgNotificationOutput.destination: messageNotificationTopic
spring.cloud.stream.bindings.msgNotificationOutput.content-type: application/json

cors:
  allowOrigin: '*'

stompBroker:
    port: 61613

logging.level.com.dharbor.set.social.chat: DEBUG
logging.level.com.dharbor.set.social.common.notifications: DEBUG


# RICHARD dev Profile
# RICHARD dev Profile
# social-chat
---
spring:
  profiles: richard
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8881
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
          enabled: true
# to avoid java.util.concurrent.TimeoutException on first hystrix execution
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
spring.cloud.stream.bindings.emailNotificationOutput.destination: emailNotificationTopic
spring.cloud.stream.bindings.emailNotificationOutput.content-type: application/json
spring.cloud.stream.bindings.msgNotificationOutput.destination: messageNotificationTopic
spring.cloud.stream.bindings.msgNotificationOutput.content-type: application/json
cors:
  allowOrigin: '*'
stompBroker:
    port: 61613
logging.level.com.dharbor.set.social.chat: DEBUG
logging.level.com.dharbor.set.social.common.notifications: DEBUG
